---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform-operator-nonprod
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: "stable-2.5"
  installPlanApproval: Manual
  name: ansible-automation-platform-operator-nonprod
  source: redhat-operators
  sourceNamespace: openshift-marketplace
